/*
 * crypto.c — Lightweight payload encryption for DNS tunnel.
 *
 * Uses a PSK-derived keystream to XOR payloads. The keystream is
 * generated by repeatedly hashing (key_hash || nonce || block_index)
 * using a simple but effective mixing function.
 *
 * This provides:
 * - Payload obfuscation (defeats pattern-matching DPI)
 * - Per-packet uniqueness via nonce (defeats replay detection)
 * - No external crypto library dependency
 *
 * This does NOT provide:
 * - Confidentiality against a determined attacker with the binary
 * - Authentication / integrity (CRC-16 in transport layer handles that)
 */

#include "crypto.h"
#include <string.h>

/* ------------------------------------------------------------------ */
/* Internal: simple hash mixing (SipHash-like rounds)                   */
/* ------------------------------------------------------------------ */

/* Rotate left 32-bit */
static uint32_t rotl32(uint32_t v, int n)
{
    return (v << n) | (v >> (32 - n));
}

/* Mix 4 × 32-bit state words. Fast, non-cryptographic but sufficient
 * to defeat DPI pattern matching on DNS payloads. */
static void mix_state(uint32_t s[4])
{
    s[0] += s[1]; s[3] ^= s[0]; s[3] = rotl32(s[3], 16);
    s[2] += s[3]; s[1] ^= s[2]; s[1] = rotl32(s[1], 12);
    s[0] += s[1]; s[3] ^= s[0]; s[3] = rotl32(s[3],  8);
    s[2] += s[3]; s[1] ^= s[2]; s[1] = rotl32(s[1],  7);
}

/* ------------------------------------------------------------------ */
/* Key derivation: hash PSK into 32-byte key_hash                       */
/* ------------------------------------------------------------------ */

void crypto_derive_key(const uint8_t *psk, size_t psk_len,
                       uint8_t out[32])
{
    uint32_t state[4];
    size_t   i;
    size_t   rounds;

    /* Initialize state with magic constants (first 4 primes × golden ratio) */
    state[0] = 0x6A09E667U;  /* sqrt(2) fractional */
    state[1] = 0xBB67AE85U;  /* sqrt(3) fractional */
    state[2] = 0x3C6EF372U;  /* sqrt(5) fractional */
    state[3] = 0xA54FF53AU;  /* sqrt(7) fractional */

    /* Absorb PSK bytes into state */
    for (i = 0; i < psk_len; i++) {
        state[i % 4] ^= ((uint32_t)psk[i]) << (8 * (i % 4));
        if ((i % 4) == 3 || i == psk_len - 1) {
            mix_state(state);
        }
    }

    /* Extra mixing rounds for avalanche */
    for (rounds = 0; rounds < 8; rounds++) {
        state[0] ^= (uint32_t)(psk_len + rounds);
        mix_state(state);
    }

    /* Serialize state to output */
    for (i = 0; i < 4; i++) {
        out[i * 4 + 0] = (uint8_t)(state[i] >> 24);
        out[i * 4 + 1] = (uint8_t)((state[i] >> 16) & 0xFFU);
        out[i * 4 + 2] = (uint8_t)((state[i] >>  8) & 0xFFU);
        out[i * 4 + 3] = (uint8_t)(state[i] & 0xFFU);
    }

    /* Expand to 32 bytes by hashing the first 16 again */
    {
        uint32_t s2[4];
        s2[0] = state[0] ^ 0xDEADBEEFU;
        s2[1] = state[1] ^ 0xCAFEBABEU;
        s2[2] = state[2] ^ 0x12345678U;
        s2[3] = state[3] ^ 0x9ABCDEF0U;
        for (rounds = 0; rounds < 4; rounds++) {
            mix_state(s2);
        }
        for (i = 0; i < 4; i++) {
            out[16 + i * 4 + 0] = (uint8_t)(s2[i] >> 24);
            out[16 + i * 4 + 1] = (uint8_t)((s2[i] >> 16) & 0xFFU);
            out[16 + i * 4 + 2] = (uint8_t)((s2[i] >>  8) & 0xFFU);
            out[16 + i * 4 + 3] = (uint8_t)(s2[i] & 0xFFU);
        }
    }
}

/* ------------------------------------------------------------------ */
/* Generate keystream block for a given nonce and block index            */
/* ------------------------------------------------------------------ */

static void generate_keystream_block(const uint8_t key_hash[32],
                                     uint16_t nonce, uint32_t block_idx,
                                     uint8_t out[16])
{
    uint32_t s[4];
    size_t   i;

    /* Seed state from key_hash */
    s[0] = ((uint32_t)key_hash[0]  << 24) | ((uint32_t)key_hash[1]  << 16) |
           ((uint32_t)key_hash[2]  <<  8) |  (uint32_t)key_hash[3];
    s[1] = ((uint32_t)key_hash[4]  << 24) | ((uint32_t)key_hash[5]  << 16) |
           ((uint32_t)key_hash[6]  <<  8) |  (uint32_t)key_hash[7];
    s[2] = ((uint32_t)key_hash[8]  << 24) | ((uint32_t)key_hash[9]  << 16) |
           ((uint32_t)key_hash[10] <<  8) |  (uint32_t)key_hash[11];
    s[3] = ((uint32_t)key_hash[12] << 24) | ((uint32_t)key_hash[13] << 16) |
           ((uint32_t)key_hash[14] <<  8) |  (uint32_t)key_hash[15];

    /* Mix in nonce and block index */
    s[0] ^= (uint32_t)nonce;
    s[1] ^= block_idx;
    s[2] ^= ((uint32_t)key_hash[16] << 24) | ((uint32_t)key_hash[17] << 16) |
             ((uint32_t)key_hash[18] <<  8) |  (uint32_t)key_hash[19];
    s[3] ^= ((uint32_t)key_hash[20] << 24) | ((uint32_t)key_hash[21] << 16) |
             ((uint32_t)key_hash[22] <<  8) |  (uint32_t)key_hash[23];

    /* 8 rounds of mixing */
    for (i = 0; i < 8; i++) {
        mix_state(s);
    }

    /* Serialize to 16-byte keystream block */
    for (i = 0; i < 4; i++) {
        out[i * 4 + 0] = (uint8_t)(s[i] >> 24);
        out[i * 4 + 1] = (uint8_t)((s[i] >> 16) & 0xFFU);
        out[i * 4 + 2] = (uint8_t)((s[i] >>  8) & 0xFFU);
        out[i * 4 + 3] = (uint8_t)(s[i] & 0xFFU);
    }
}

/* ------------------------------------------------------------------ */
/* XOR data with keystream                                              */
/* ------------------------------------------------------------------ */

static void xor_keystream(const uint8_t key_hash[32], uint16_t nonce,
                           const uint8_t *in, uint8_t *out, size_t len)
{
    uint8_t  ks_block[16];
    uint32_t block_idx = 0;
    size_t   pos       = 0;
    size_t   ks_pos    = 16; /* force generation on first byte */

    while (pos < len) {
        if (ks_pos >= 16) {
            generate_keystream_block(key_hash, nonce, block_idx, ks_block);
            block_idx++;
            ks_pos = 0;
        }
        out[pos] = in[pos] ^ ks_block[ks_pos];
        pos++;
        ks_pos++;
    }
}

/* ------------------------------------------------------------------ */
/* Public API                                                           */
/* ------------------------------------------------------------------ */

void crypto_init(crypto_ctx_t *ctx, const uint8_t *psk, size_t psk_len)
{
    memset(ctx, 0, sizeof(*ctx));

    if (!psk || psk_len == 0) {
        ctx->enabled = 0;
        return;
    }

    crypto_derive_key(psk, psk_len, ctx->key_hash);
    ctx->tx_nonce = 0;
    ctx->rx_nonce = 0;
    ctx->enabled  = 1;
}

int crypto_encrypt(crypto_ctx_t *ctx,
                   const uint8_t *data, size_t data_len,
                   uint8_t *out, size_t out_cap)
{
    uint16_t nonce;

    if (!ctx || !ctx->enabled) {
        /* Pass through: just copy data as-is */
        if (data_len > out_cap) {
            return -1;
        }
        memcpy(out, data, data_len);
        return (int)data_len;
    }

    if (!data || !out) {
        return -1;
    }

    if (data_len + CRYPTO_NONCE_SIZE > out_cap) {
        return -1;
    }

    nonce = ctx->tx_nonce++;

    /* Prepend nonce */
    out[0] = (uint8_t)(nonce >> 8);
    out[1] = (uint8_t)(nonce & 0xFFU);

    /* Encrypt payload */
    xor_keystream(ctx->key_hash, nonce, data, out + CRYPTO_NONCE_SIZE, data_len);

    return (int)(data_len + CRYPTO_NONCE_SIZE);
}

int crypto_decrypt(crypto_ctx_t *ctx,
                   const uint8_t *buf, size_t buf_len,
                   uint8_t *out, size_t out_cap)
{
    uint16_t nonce;
    size_t   data_len;

    if (!ctx || !ctx->enabled) {
        /* Pass through */
        if (buf_len > out_cap) {
            return -1;
        }
        memcpy(out, buf, buf_len);
        return (int)buf_len;
    }

    if (!buf || !out) {
        return -1;
    }

    if (buf_len < CRYPTO_NONCE_SIZE) {
        return -1;
    }

    nonce    = (uint16_t)((buf[0] << 8) | buf[1]);
    data_len = buf_len - CRYPTO_NONCE_SIZE;

    if (data_len > out_cap) {
        return -1;
    }

    /* Update rx_nonce for tracking (no strict anti-replay for now,
     * because DNS retransmits are common — like dnscat2's approach) */
    ctx->rx_nonce = nonce;

    /* Decrypt */
    xor_keystream(ctx->key_hash, nonce,
                  buf + CRYPTO_NONCE_SIZE, out, data_len);

    return (int)data_len;
}
